# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b0e44c9944eed32605fa70b7f9344a7600872408555d4c6c23e10955294c2dd2f594f0609b612fb078977124dcf51cc0943e751bee943de44a08e0881d887df

test:
  secret_key_base: 695281d91f53fb2906a75e887aa6d844bd6f7fb1d9215af9a05cee5337e669a685f6c86213f74f22760366509956253389b449a9a8226d3647151858afad03f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
